---
- name: Install Certbot PPA
  apt_repository:
    repo: 'ppa:certbot/certbot'

- name: Install certbot
  apt:
   name: certbot
   update_cache: yes

- name: Install certbot-dns-rfc2136 plugins
  pip:
	  name: certbot-dns-rfc2136

- name: register certbot
  command: certbot register --agree-tos -m {{ email|quote }} --no-eff-email
  args:
    creates: /etc/letsencrypt/accounts/acme-v01.api.letsencrypt.org/directory/*/regr.json